Repository opensearch-project/opensearch-learning-to-rank-base, pull requests merged in 2025-04, with the labels that each got.

#156 Support phasing off SecurityManager usage in favor of Java Agent
  build.gradle
Labels: v3.0.0, release

#169 Remove beta1 qualifier
  build.gradle
Labels: v3.0.0, release, backport main

#171 Address http5client CVE, use core's dependency
  build.gradle
Labels: backport 3.0
